### ISSUE TITLE
Many questions...

### ISSUE THREAD

**Issue by dnkennedy** [DCAN-Labs/BIBSnet#117]
### A short summary of a question you have for the BIBSnet development team.

Hi, I'm new to BIBSnet and have sooo many questions:
1. What's the base place to ask questions? Here in issues? at Neurostars?
2. Is there a command flag to get the version? Anything that works via 'latest' scares the bejesus out of me for version tracking. a --version flag (or something) would be helpful.
3. Age: the documentation talks about the places that age can be, but there is also a command line argument for -age. I did a run when I set '-age 9' and the message on the console says: 

> INFO 2024-07-19 13:12:58,375: Now running prebibsnet stage on:
> {'subject': 'sub-BB03601', 'session': 'ses-1', 'age_months': 0, 'brain_z_size': 121, 'has_T1w': True, 'has_T2w': True, 'model': 526}
which make me anxious about my manual setting of the age. BTW, my participants dies have age for this subject set at .75 [years]. Age in BIDS/participants.tsv is required to be in years, no?
4. It might be in the readthedocs but can you tell me what happens when we happen to run many (~4) T1's AND T2's? Does it select the best pair? Does it average them? Should I be doing something to pre-identify the best?

OK, enough questions for now. Many apologies in advance for any dumb questions...

**Comment by LuciMoore** [comment]
Hi, @dnkennedy. Thanks so much for your patience! 

1. The best place to ask questions is by posting GitHub issues as you have done
2. Version: understandable! You can find the BIBSNet version in the derivative json files
3. Age: for your use case, make sure that the age in the participants.tsv (and sessions.tsv if relevant) is also in months (you don't need to use the --age flag if the information is already in the participants.tsv file). But you make a good point - technically in order to be BIDS valid, there needs to be a sidecar json present for the tsv files (participants.tsv, sessions.tsv, scans.tsv, etc) that specifies months as the unit for the age column (since BIDS default is years). or better yet, update the code to be flexible to age in years or months. So I'll open a separate issue for that 
4. Multiple anats: all anats for T1/T2 present are averaged, so I would definitely remove any bad anatomicals from the BIDS input dir for now while we continue development

Thanks so much for your questions! There are many areas of refinement needed and the documentation needs clarification as well, so we'll continue to work on that. Please follow up if further clarification is needed!

**Comment by LuciMoore** [comment]
@dnkennedy our latest release, [v3.4.1](https://github.com/DCAN-Labs/BIBSnet/releases/tag/3.4.1), has some major updates that makes BIBSNet more user-friendly (for example, it no longer requires you to specify age) and also generates higher quality outputs. The [documentation](https://bibsnet.readthedocs.io/en/latest/) is also updated. I will close this issue for now, but please reach out if you have further queries
