### ISSUE TITLE
Edit DockerHub Documentation

### ISSUE THREAD

**Issue by erikglee** [DCAN-Labs/BIBSnet#13]
### What happened?

The current DockerHub documentation refers to FSL as FreeSurferLearner, where I think you mean to say FMRIB Software Library (see below):

_"fsl_bin_path": string, a valid absolute path to existing bin directory in [FreeSurferLearner (FSL)](https://fsl.fmrib.ox.ac.uk/fsl/fslwiki/). Example: "/opt/fsl-6.0.5.1/bin/"_

### What command did you use?

```shell
NA
```

### What version of CABINET are you using?

NA

**Comment by GregConan** [comment]
[On GitHub, the documentation says FMRIB Software Library](https://github.com/DCAN-Labs/CABINET/#common-parameters-used-by-multiple-stages-within-cabinet), but [on DockerHub it still says FreeSurferLearner](https://hub.docker.com/r/dcanumn/cabinet#!). Presumably that is because the DockerHub documentation was copy-pasted from an earlier version of the CABINET README. @tjhendrickson Would you be able to update the DockerHub documentation to match the latest README, or set it up to automatically update?

**Comment by rosemccollum** [comment]
Dockerhub no longer has documentation (besides the diagram of what CABINET does), our readthedocs is now linked.
