### ISSUE TITLE
Issues with Segmentation and Surfaces Generated from BIBSNET

### ISSUE THREAD

**Issue by henrycikanek** [DCAN-Labs/BIBSnet#47]
### What happened?

After running our subjects data through CABINET, and then utilizing CABINET's segmentation generated by BIBSNET to process our subjects through RECON-ALL function to generate surfaces we began to detect a variety of labeling and alignment issues. The subject's screenshots below are indicative of some of the issues we observed. We noticed that segmentation done by bibsnet was commonly mislabeling left and right hemispheres, as well as delineating different views incorrectly (such as axial as coronal etc.). Really appreciate your guys help, and all that you do! So far overall CABINET has been awesome, excited to keep using it and hopefully help to improve it as well:).

### What command did you use?

```shell
I wrote a script that loops over a batch of bids formatted subjects. This is the command used:

    docker run -t \
        -v "${input_dir}:/input" \
        -v "${output_dir}:/output" \
        -v "${param_file}:/param_file.json" \
        dcanumn/cabinet:t1-only_t2-only \
        /input /output \
        participant \
        -participant "${participant_id}" \
        -ses "${session}" \
        -age "${age}" \
        -jargs /param_file.json \
        --end postbibsnet \
        -v

Recon-all command used:

    infant_recon_all --s ${sub} --age ${age} \
    --inputfile ${SUBJECTS_DIR}/${sub}/mprage.nii.gz \
    --segfile ${SUBJECTS_DIR}/${sub}/aseg.nii.gz \
    --masked ${SUBJECTS_DIR}/${sub}/mprage.nii.gz
```

### What version of CABINET are you using?

dcanumn/cabinet      t1-only_t2-only   a67201fd14b6   6 months ago   38.4GB

### Add any additional information or context about the problem here.

recon-all:

![](https://files.slack.com/files-pri/T96LTDWKH-F059P0CG3N1/1017__recon-all_.png)

bibsnet:

![](https://files.slack.com/files-pri/T96LTDWKH-F059BCAV5GF/1017_bibsnet.png)

**Comment by audreymhoughton** [comment]
Hi @henrycikanek - that is a outdated version of CABINET that we no longer support. Please download the latest version, 2.4.0, from our dockerhub. Thanks!

**Comment by audreymhoughton** [comment]
@henrycikanek - I am going to close this issue. Please re-open it if the problem persists.

**Comment by henrycikanek** [comment]
Hey went ahead and updated. Just looking for a few quick points of clarification:

1. Inside of the work dir are the files named .../bibsnet/ input/0000 and 0001 the co-registered T1 & T2 respectively?
2. Are the files located inside of workdir/prebibsnet/(subject folder)/resized xfms & ACPC_align the coregistered T2?

The main reason I am asking is that my lab is seeking to manually correct segmentation/surfaces utilizing the coregistered T2. Also, apologies for asking the question here could not find another place to ask. Appreciate all the help! Sorry if my question is poorly worded as well am a SWE by trade not a neurologist. Thank you for all you and your teams work!

**Comment by ericfeczko** [comment]
Hey Henry!

1. there are different co-registration algorithms used in prebibsnet, a selection process determines which approach is ultimately used -- the bibsnet/inputs are a copy of the preselected co-registered T1 & T2. If you use these, you should be fine.

2. The ACPC_align is one of these processes. In addition the xfms in this folder will enable you to translate the T1 and the T2 from/to native/co-registered spaces :) 

We really appreciate the use of github issues for asking these questions -- you are always welcome to post a separate issue, so that others can more easily note different issues :) Continuing the same one is fine too.

To circle back to the initial post -- we are working on a new version of BIBSNET, which will be incorporated into CABINET. The new version will have a new trained model that may be more generalizable than prior models, so I recommend testing the new version out. We anticipate that this new version should be ready within two months at the worst.

**Comment by audreymhoughton** [comment]
@henrycikanek, it is worth noting that a model has been added since the container you were running above as well, though. So I would update to 2.4.0 and then wait for the new version @ericfeczko refers to here.
