### ISSUE TITLE
Generated only one half of the aseg file

### ISSUE THREAD

**Issue by yanbin-niu** [DCAN-Labs/BIBSnet#75]
### What happened?

Dear Cabinet Experts,

I ran cabinet through a T2w for segmentation. While the T2w quality was good, the output aseg file, unfortunately, only had one half of the brain.

This is puzzling, and I'm reaching out with the hope of getting insights from you -- any idea about the potential reasons?

Please note that this is the first time my team met this issue. We'd greatly appreciate your thoughts on what might be causing this.
Thank you in advance!

<img width="1300" alt="image" src="https://github.com/DCAN-Labs/CABINET/assets/79607547/71c982c2-bac9-4d56-8da7-7d59f08edf08">

### What command did you use?

```shell
docker run -t -v /Users/sealab/Documents/MRI/ABC/newborn/bids:/input -v /Users/sealab/Documents/MRI/ABC/newborn/derivatives/CABINET:/output -v /Users/sealab/Documents/MRI/ABC/newborn/derivatives/work/cabinet_work:/work_tmp -v /Users/sealab/Documents/MRI/BABIES/CABINET_parameter/parameter-file-container.json:/param_file.json dcanumn/cabinet:2.4.2 /input /output participant -participant sub-12020 -ses ses-newborn -age 1 -jargs /param_file.json -end postbibsnet -start prebibsnet -w /work_tmp -v
```

### What version of CABINET are you using?

2.4.2

**Comment by ericfeczko** [comment]
Hey @yanbin-niu,

There are two possibilities:

1) The crop may have been off on this particular scan -- I would examine prebibsnet to see if the brain was cropped

2) There is a known bug with some brains -- which is an issue with the post-processing step during BIBSNET -- and are working on the revision. Briefly, there is a post-processing step that addresses some minor labeling issues where the hemispheres get swapped (chirality correction). There is another post-processing step that is occuring prior to chirality correction that removes mislabeled components. Simply put, we just need to flip these steps. This will be tackled in the next version of BIBSNET, which will then be tested within  CABINET. Due to other ongoing projects, we hope to have this tackled within the next two months.

**Comment by yanbin-niu** [comment]
Hey @ericfeczko, thanks for the quick response! I just took a look at the work folder, and you're right, it got cut off right after the crop prebibsnet step. Now I'm wondering if you have any ideas on what we could do to fix this in this situation? Your input would be highly appreciated!

**Comment by ericfeczko** [comment]
By default CABINET will automatically crop based on the infant's age -- however this crop is also based on scan protocols targeted for studies like HBCD and may not apply in all situations. 

In such cases, there's an optional `-z` flag that can be used to override and force a specific crop. You'll need to provide the length of the brain in the z direction.

https://cabinet.readthedocs.io/en/latest/usage/

**Comment by yanbin-niu** [comment]
@ericfeczko I just tried and it worked! thanks!
